
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentservice-deployment
  labels:
    app: documentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentservice
  template:
    metadata:
      labels:
        app: documentservice
    spec:
      containers:
        - name: documentservice
          image: 212.85.1.77:5000/businessservice:latest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
    