
apiVersion: v1
kind: Service
metadata:
    name: documentservice-service
    labels:
        app: documentservice
spec:
    type: NodePort
    selector:
        app: documentservice  # Replace with your application's label
    ports:
        - port: 8080        # The port your application listens on internally
          targetPort: 8080  # The port within the pod
          nodePort: 30086
          protocol: TCP
    