
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myschool-deployment
  labels:
    app: myschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myschool
  template:
    metadata:
      labels:
        app: myschool
    spec:
      containers:
        - name: sdasdasd
          image: hgasdgajd
          imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
    