
apiVersion: v1
kind: Service
metadata:
    name: test3-service
    labels:
        app: test3
spec:
    type: NodePort
    selector:
        app: test3  # Replace with your application's label
    ports:
        - port: 8080        # The port your application listens on internally
          targetPort: 8080  # The port within the pod
          nodePort: 3005
          protocol: TCP
    